# TCL File Generated by Component Editor 14.0
# Thu Dec 11 22:11:38 CET 2014
# DO NOT MODIFY


# 
# LT24_CTRL "LT24_CTRL" v1.4
#  2014.12.11.22:11:38
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module LT24_CTRL
# 
set_module_property DESCRIPTION ""
set_module_property NAME LT24_CTRL
set_module_property VERSION 1.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LT24_CTRL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LT24_Module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LT24_Module.vhd VHDL PATH ../HDL/LT24_Module.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chip_select chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read_data_slave readdata Output 32
add_interface_port avalon_slave_0 write_data_slave writedata Input 32
add_interface_port avalon_slave_0 address_slave address Input 3
add_interface_port avalon_slave_0 read_slave read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point lcd_reset_n
# 
add_interface lcd_reset_n conduit end
set_interface_property lcd_reset_n associatedClock clock
set_interface_property lcd_reset_n associatedReset reset
set_interface_property lcd_reset_n ENABLED true
set_interface_property lcd_reset_n EXPORT_OF ""
set_interface_property lcd_reset_n PORT_NAME_MAP ""
set_interface_property lcd_reset_n CMSIS_SVD_VARIABLES ""
set_interface_property lcd_reset_n SVD_ADDRESS_GROUP ""

add_interface_port lcd_reset_n lcd_reset_n export Output 1


# 
# connection point lcd_on
# 
add_interface lcd_on conduit end
set_interface_property lcd_on associatedClock clock
set_interface_property lcd_on associatedReset reset
set_interface_property lcd_on ENABLED true
set_interface_property lcd_on EXPORT_OF ""
set_interface_property lcd_on PORT_NAME_MAP ""
set_interface_property lcd_on CMSIS_SVD_VARIABLES ""
set_interface_property lcd_on SVD_ADDRESS_GROUP ""

add_interface_port lcd_on lcd_on export Output 1


# 
# connection point csx
# 
add_interface csx conduit end
set_interface_property csx associatedClock clock
set_interface_property csx associatedReset reset
set_interface_property csx ENABLED true
set_interface_property csx EXPORT_OF ""
set_interface_property csx PORT_NAME_MAP ""
set_interface_property csx CMSIS_SVD_VARIABLES ""
set_interface_property csx SVD_ADDRESS_GROUP ""

add_interface_port csx csx export Output 1


# 
# connection point dcx
# 
add_interface dcx conduit end
set_interface_property dcx associatedClock clock
set_interface_property dcx associatedReset reset
set_interface_property dcx ENABLED true
set_interface_property dcx EXPORT_OF ""
set_interface_property dcx PORT_NAME_MAP ""
set_interface_property dcx CMSIS_SVD_VARIABLES ""
set_interface_property dcx SVD_ADDRESS_GROUP ""

add_interface_port dcx dcx export Output 1


# 
# connection point wrx
# 
add_interface wrx conduit end
set_interface_property wrx associatedClock clock
set_interface_property wrx associatedReset reset
set_interface_property wrx ENABLED true
set_interface_property wrx EXPORT_OF ""
set_interface_property wrx PORT_NAME_MAP ""
set_interface_property wrx CMSIS_SVD_VARIABLES ""
set_interface_property wrx SVD_ADDRESS_GROUP ""

add_interface_port wrx wrx export Output 1


# 
# connection point rdx
# 
add_interface rdx conduit end
set_interface_property rdx associatedClock clock
set_interface_property rdx associatedReset reset
set_interface_property rdx ENABLED true
set_interface_property rdx EXPORT_OF ""
set_interface_property rdx PORT_NAME_MAP ""
set_interface_property rdx CMSIS_SVD_VARIABLES ""
set_interface_property rdx SVD_ADDRESS_GROUP ""

add_interface_port rdx rdx export Output 1


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset reset
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_out export Output 16


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address_master address Output 32
add_interface_port avalon_master read_master read Output 1
add_interface_port avalon_master read_data_master readdata Input 32
add_interface_port avalon_master wait_request waitrequest Input 1
add_interface_port avalon_master burst_cnt burstcount Output 7
add_interface_port avalon_master read_data_valid readdatavalid Input 1
add_interface_port avalon_master byte_enable_n byteenable_n Output 4


# 
# connection point wait_request_master_debug
# 
add_interface wait_request_master_debug conduit end
set_interface_property wait_request_master_debug associatedClock clock
set_interface_property wait_request_master_debug associatedReset reset
set_interface_property wait_request_master_debug ENABLED true
set_interface_property wait_request_master_debug EXPORT_OF ""
set_interface_property wait_request_master_debug PORT_NAME_MAP ""
set_interface_property wait_request_master_debug CMSIS_SVD_VARIABLES ""
set_interface_property wait_request_master_debug SVD_ADDRESS_GROUP ""

add_interface_port wait_request_master_debug wait_request_debug export Output 1


# 
# connection point read_master_debug
# 
add_interface read_master_debug conduit end
set_interface_property read_master_debug associatedClock clock
set_interface_property read_master_debug associatedReset reset
set_interface_property read_master_debug ENABLED true
set_interface_property read_master_debug EXPORT_OF ""
set_interface_property read_master_debug PORT_NAME_MAP ""
set_interface_property read_master_debug CMSIS_SVD_VARIABLES ""
set_interface_property read_master_debug SVD_ADDRESS_GROUP ""

add_interface_port read_master_debug read_master_debug export Output 1


# 
# connection point read_data_master_debug
# 
add_interface read_data_master_debug conduit end
set_interface_property read_data_master_debug associatedClock clock
set_interface_property read_data_master_debug associatedReset reset
set_interface_property read_data_master_debug ENABLED true
set_interface_property read_data_master_debug EXPORT_OF ""
set_interface_property read_data_master_debug PORT_NAME_MAP ""
set_interface_property read_data_master_debug CMSIS_SVD_VARIABLES ""
set_interface_property read_data_master_debug SVD_ADDRESS_GROUP ""

add_interface_port read_data_master_debug read_data_master_debug export Output 32


# 
# connection point address_master_debug
# 
add_interface address_master_debug conduit end
set_interface_property address_master_debug associatedClock clock
set_interface_property address_master_debug associatedReset reset
set_interface_property address_master_debug ENABLED true
set_interface_property address_master_debug EXPORT_OF ""
set_interface_property address_master_debug PORT_NAME_MAP ""
set_interface_property address_master_debug CMSIS_SVD_VARIABLES ""
set_interface_property address_master_debug SVD_ADDRESS_GROUP ""

add_interface_port address_master_debug address_master_debug export Output 32

