# TCL File Generated by Component Editor 14.0
# Thu Dec 11 22:07:51 CET 2014
# DO NOT MODIFY


# 
# Camera_Interface "Camera_Interface" v1.0
#  2014.12.11.22:07:51
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module Camera_Interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME Camera_Interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Camera_Interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CameraInterface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonInterfaces.vhd VHDL PATH ../vhdl/AvalonInterfaces.vhd
add_fileset_file CameraController.vhd VHDL PATH ../vhdl/CameraController.vhd
add_fileset_file CameraInterface.vhd VHDL PATH ../vhdl/CameraInterface.vhd TOP_LEVEL_FILE
add_fileset_file fifo.vhd VHDL PATH ../vhdl/fifo.vhd
add_fileset_file i2c_clkgen.vhd VHDL PATH ../vhdl/i2c_clkgen.vhd
add_fileset_file i2c_core.vhd VHDL PATH ../vhdl/i2c_core.vhd
add_fileset_file i2c_interface.vhd VHDL PATH ../vhdl/i2c_interface.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CPU_CLK
# 
add_interface CPU_CLK clock end
set_interface_property CPU_CLK clockRate 50000000
set_interface_property CPU_CLK ENABLED true
set_interface_property CPU_CLK EXPORT_OF ""
set_interface_property CPU_CLK PORT_NAME_MAP ""
set_interface_property CPU_CLK CMSIS_SVD_VARIABLES ""
set_interface_property CPU_CLK SVD_ADDRESS_GROUP ""

add_interface_port CPU_CLK CPUCLKxCI clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CPU_CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RSTxRBI reset_n Input 1


# 
# connection point Camera_Slave
# 
add_interface Camera_Slave avalon end
set_interface_property Camera_Slave addressUnits WORDS
set_interface_property Camera_Slave associatedClock CPU_CLK
set_interface_property Camera_Slave associatedReset RESET
set_interface_property Camera_Slave bitsPerSymbol 8
set_interface_property Camera_Slave burstOnBurstBoundariesOnly false
set_interface_property Camera_Slave burstcountUnits WORDS
set_interface_property Camera_Slave explicitAddressSpan 0
set_interface_property Camera_Slave holdTime 0
set_interface_property Camera_Slave linewrapBursts false
set_interface_property Camera_Slave maximumPendingReadTransactions 0
set_interface_property Camera_Slave maximumPendingWriteTransactions 0
set_interface_property Camera_Slave readLatency 0
set_interface_property Camera_Slave readWaitTime 1
set_interface_property Camera_Slave setupTime 0
set_interface_property Camera_Slave timingUnits Cycles
set_interface_property Camera_Slave writeWaitTime 0
set_interface_property Camera_Slave ENABLED true
set_interface_property Camera_Slave EXPORT_OF ""
set_interface_property Camera_Slave PORT_NAME_MAP ""
set_interface_property Camera_Slave CMSIS_SVD_VARIABLES ""
set_interface_property Camera_Slave SVD_ADDRESS_GROUP ""

add_interface_port Camera_Slave ASlaveChipSelectxSI chipselect Input 1
add_interface_port Camera_Slave ASlaveAddressxDI address Input 3
add_interface_port Camera_Slave ASlaveReadxSI read Input 1
add_interface_port Camera_Slave ASlaveReadDataxDO readdata Output 32
add_interface_port Camera_Slave ASlaveWritexSI write Input 1
add_interface_port Camera_Slave ASlaveWriteDataxDI writedata Input 32
set_interface_assignment Camera_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment Camera_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Camera_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Camera_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Camera_Master
# 
add_interface Camera_Master avalon start
set_interface_property Camera_Master addressUnits SYMBOLS
set_interface_property Camera_Master associatedClock CPU_CLK
set_interface_property Camera_Master associatedReset RESET
set_interface_property Camera_Master bitsPerSymbol 8
set_interface_property Camera_Master burstOnBurstBoundariesOnly false
set_interface_property Camera_Master burstcountUnits WORDS
set_interface_property Camera_Master doStreamReads false
set_interface_property Camera_Master doStreamWrites false
set_interface_property Camera_Master holdTime 0
set_interface_property Camera_Master linewrapBursts false
set_interface_property Camera_Master maximumPendingReadTransactions 0
set_interface_property Camera_Master maximumPendingWriteTransactions 0
set_interface_property Camera_Master readLatency 0
set_interface_property Camera_Master readWaitTime 1
set_interface_property Camera_Master setupTime 0
set_interface_property Camera_Master timingUnits Cycles
set_interface_property Camera_Master writeWaitTime 0
set_interface_property Camera_Master ENABLED true
set_interface_property Camera_Master EXPORT_OF ""
set_interface_property Camera_Master PORT_NAME_MAP ""
set_interface_property Camera_Master CMSIS_SVD_VARIABLES ""
set_interface_property Camera_Master SVD_ADDRESS_GROUP ""

add_interface_port Camera_Master AMasterAddressxDO address Output 32
add_interface_port Camera_Master AMasterByteEnablexDBO byteenable_n Output 4
add_interface_port Camera_Master AMasterWritexSO write Output 1
add_interface_port Camera_Master AMasterWriteDataxDO writedata Output 32
add_interface_port Camera_Master AMasterWaitRequestxSI waitrequest Input 1
add_interface_port Camera_Master AMasterBurstCountxSO burstcount Output 5


# 
# connection point Camera_PIXCLK
# 
add_interface Camera_PIXCLK conduit end
set_interface_property Camera_PIXCLK associatedClock ""
set_interface_property Camera_PIXCLK associatedReset ""
set_interface_property Camera_PIXCLK ENABLED true
set_interface_property Camera_PIXCLK EXPORT_OF ""
set_interface_property Camera_PIXCLK PORT_NAME_MAP ""
set_interface_property Camera_PIXCLK CMSIS_SVD_VARIABLES ""
set_interface_property Camera_PIXCLK SVD_ADDRESS_GROUP ""

add_interface_port Camera_PIXCLK CameraPIXCLKxCI export Input 1


# 
# connection point Camera_DATA
# 
add_interface Camera_DATA conduit end
set_interface_property Camera_DATA associatedClock ""
set_interface_property Camera_DATA associatedReset ""
set_interface_property Camera_DATA ENABLED true
set_interface_property Camera_DATA EXPORT_OF ""
set_interface_property Camera_DATA PORT_NAME_MAP ""
set_interface_property Camera_DATA CMSIS_SVD_VARIABLES ""
set_interface_property Camera_DATA SVD_ADDRESS_GROUP ""

add_interface_port Camera_DATA CameraDataxDI export Input 12


# 
# connection point Camera_LVAL
# 
add_interface Camera_LVAL conduit end
set_interface_property Camera_LVAL associatedClock ""
set_interface_property Camera_LVAL associatedReset ""
set_interface_property Camera_LVAL ENABLED true
set_interface_property Camera_LVAL EXPORT_OF ""
set_interface_property Camera_LVAL PORT_NAME_MAP ""
set_interface_property Camera_LVAL CMSIS_SVD_VARIABLES ""
set_interface_property Camera_LVAL SVD_ADDRESS_GROUP ""

add_interface_port Camera_LVAL CameraLVALxSI export Input 1


# 
# connection point Camera_FVAL
# 
add_interface Camera_FVAL conduit end
set_interface_property Camera_FVAL associatedClock ""
set_interface_property Camera_FVAL associatedReset ""
set_interface_property Camera_FVAL ENABLED true
set_interface_property Camera_FVAL EXPORT_OF ""
set_interface_property Camera_FVAL PORT_NAME_MAP ""
set_interface_property Camera_FVAL CMSIS_SVD_VARIABLES ""
set_interface_property Camera_FVAL SVD_ADDRESS_GROUP ""

add_interface_port Camera_FVAL CameraFVALxSI export Input 1


# 
# connection point Camera_SCL
# 
add_interface Camera_SCL conduit end
set_interface_property Camera_SCL associatedClock ""
set_interface_property Camera_SCL associatedReset ""
set_interface_property Camera_SCL ENABLED true
set_interface_property Camera_SCL EXPORT_OF ""
set_interface_property Camera_SCL PORT_NAME_MAP ""
set_interface_property Camera_SCL CMSIS_SVD_VARIABLES ""
set_interface_property Camera_SCL SVD_ADDRESS_GROUP ""

add_interface_port Camera_SCL CameraSCLxSI export Bidir 1


# 
# connection point Camera_SDA
# 
add_interface Camera_SDA conduit end
set_interface_property Camera_SDA associatedClock ""
set_interface_property Camera_SDA associatedReset ""
set_interface_property Camera_SDA ENABLED true
set_interface_property Camera_SDA EXPORT_OF ""
set_interface_property Camera_SDA PORT_NAME_MAP ""
set_interface_property Camera_SDA CMSIS_SVD_VARIABLES ""
set_interface_property Camera_SDA SVD_ADDRESS_GROUP ""

add_interface_port Camera_SDA CameraSDATAxSI export Bidir 1

