# TCL File Generated by Component Editor 14.1
# Thu May 14 23:49:15 CEST 2015
# DO NOT MODIFY


# 
# vga_module "vga_module" v2.0
#  2015.05.14.23:49:15
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module vga_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_module
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_module.vhd VHDL PATH ../vhdl/vga_module.vhd TOP_LEVEL_FILE
add_fileset_file vga_controller.vhd VHDL PATH ../vhdl/vga_controller.vhd
add_fileset_file vga_dma.vhd VHDL PATH ../vhdl/vga_dma.vhd
add_fileset_file vga_fifo.vhd VHDL PATH ../vhdl/vga_fifo.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock main_clk
set_interface_property avalon_master associatedReset reset_n
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master am_waitrequest waitrequest Input 1
add_interface_port avalon_master am_readdata readdata Input 32
add_interface_port avalon_master am_read read Output 1
add_interface_port avalon_master am_byteenable byteenable Output 4
add_interface_port avalon_master am_address address Output 32


# 
# connection point vga_hs
# 
add_interface vga_hs conduit end
set_interface_property vga_hs associatedClock pixel_clk
set_interface_property vga_hs associatedReset reset_n
set_interface_property vga_hs ENABLED true
set_interface_property vga_hs EXPORT_OF ""
set_interface_property vga_hs PORT_NAME_MAP ""
set_interface_property vga_hs CMSIS_SVD_VARIABLES ""
set_interface_property vga_hs SVD_ADDRESS_GROUP ""

add_interface_port vga_hs vga_hs export Output 1


# 
# connection point pixel_clk
# 
add_interface pixel_clk clock end
set_interface_property pixel_clk clockRate 25000000
set_interface_property pixel_clk ENABLED true
set_interface_property pixel_clk EXPORT_OF ""
set_interface_property pixel_clk PORT_NAME_MAP ""
set_interface_property pixel_clk CMSIS_SVD_VARIABLES ""
set_interface_property pixel_clk SVD_ADDRESS_GROUP ""

add_interface_port pixel_clk pixel_clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock main_clk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1


# 
# connection point main_clk
# 
add_interface main_clk clock end
set_interface_property main_clk clockRate 100000000
set_interface_property main_clk ENABLED true
set_interface_property main_clk EXPORT_OF ""
set_interface_property main_clk PORT_NAME_MAP ""
set_interface_property main_clk CMSIS_SVD_VARIABLES ""
set_interface_property main_clk SVD_ADDRESS_GROUP ""

add_interface_port main_clk clk clk Input 1


# 
# connection point vga_r
# 
add_interface vga_r conduit end
set_interface_property vga_r associatedClock pixel_clk
set_interface_property vga_r associatedReset reset_n
set_interface_property vga_r ENABLED true
set_interface_property vga_r EXPORT_OF ""
set_interface_property vga_r PORT_NAME_MAP ""
set_interface_property vga_r CMSIS_SVD_VARIABLES ""
set_interface_property vga_r SVD_ADDRESS_GROUP ""

add_interface_port vga_r vga_r export Output 8


# 
# connection point vga_g
# 
add_interface vga_g conduit end
set_interface_property vga_g associatedClock pixel_clk
set_interface_property vga_g associatedReset reset_n
set_interface_property vga_g ENABLED true
set_interface_property vga_g EXPORT_OF ""
set_interface_property vga_g PORT_NAME_MAP ""
set_interface_property vga_g CMSIS_SVD_VARIABLES ""
set_interface_property vga_g SVD_ADDRESS_GROUP ""

add_interface_port vga_g vga_g export Output 8


# 
# connection point vga_b
# 
add_interface vga_b conduit end
set_interface_property vga_b associatedClock pixel_clk
set_interface_property vga_b associatedReset reset_n
set_interface_property vga_b ENABLED true
set_interface_property vga_b EXPORT_OF ""
set_interface_property vga_b PORT_NAME_MAP ""
set_interface_property vga_b CMSIS_SVD_VARIABLES ""
set_interface_property vga_b SVD_ADDRESS_GROUP ""

add_interface_port vga_b vga_b export Output 8


# 
# connection point vga_clk
# 
add_interface vga_clk conduit end
set_interface_property vga_clk associatedClock pixel_clk
set_interface_property vga_clk associatedReset reset_n
set_interface_property vga_clk ENABLED true
set_interface_property vga_clk EXPORT_OF ""
set_interface_property vga_clk PORT_NAME_MAP ""
set_interface_property vga_clk CMSIS_SVD_VARIABLES ""
set_interface_property vga_clk SVD_ADDRESS_GROUP ""

add_interface_port vga_clk vga_clk export Output 1


# 
# connection point vga_sync_n
# 
add_interface vga_sync_n conduit end
set_interface_property vga_sync_n associatedClock pixel_clk
set_interface_property vga_sync_n associatedReset reset_n
set_interface_property vga_sync_n ENABLED true
set_interface_property vga_sync_n EXPORT_OF ""
set_interface_property vga_sync_n PORT_NAME_MAP ""
set_interface_property vga_sync_n CMSIS_SVD_VARIABLES ""
set_interface_property vga_sync_n SVD_ADDRESS_GROUP ""

add_interface_port vga_sync_n vga_sync_n export Output 1


# 
# connection point vga_blank_n
# 
add_interface vga_blank_n conduit end
set_interface_property vga_blank_n associatedClock pixel_clk
set_interface_property vga_blank_n associatedReset reset_n
set_interface_property vga_blank_n ENABLED true
set_interface_property vga_blank_n EXPORT_OF ""
set_interface_property vga_blank_n PORT_NAME_MAP ""
set_interface_property vga_blank_n CMSIS_SVD_VARIABLES ""
set_interface_property vga_blank_n SVD_ADDRESS_GROUP ""

add_interface_port vga_blank_n vga_blank_n export Output 1


# 
# connection point vga_vs
# 
add_interface vga_vs conduit end
set_interface_property vga_vs associatedClock pixel_clk
set_interface_property vga_vs associatedReset reset_n
set_interface_property vga_vs ENABLED true
set_interface_property vga_vs EXPORT_OF ""
set_interface_property vga_vs PORT_NAME_MAP ""
set_interface_property vga_vs CMSIS_SVD_VARIABLES ""
set_interface_property vga_vs SVD_ADDRESS_GROUP ""

add_interface_port vga_vs vga_vs export Output 1

